name: nwis2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit>=1.0.0
  - streamlit-keplergl>=0.1.4
  - pandas>=1.3.0
  - plotly>=5.0.0
  - geopandas>=0.10.0
  - pip
  - pip:
    - keplergl==0.3.7  # Specific version required for compatibility
    - watchdog  # For better Streamlit performance
