[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
runOnSave = false

[theme]
base = "light"
primaryColor = "#2b8cbe"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f6f6"
textColor = "#222222"
font = "sans serif"
